/** Issue with Auto-Generated Files not Adding Controls **/

DELETE FROM "DBPARAMETER"."PARAM";

INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('person', 'org.esco.grouperui.group.members.map', 'person', 'esco:ldap', 'Propriétés de groupe - Membres - détermination type personne');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('group', 'org.esco.grouperui.group.members.map', 'group', 'g:gsa', 'PPropriétés de groupe - Membres - détermination type groupe');

INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('cols', 'org.esco.grouperui.group.members.person.col', '#{attr[''displayName'']}', '#{attr[''displayName'']}', 'No description');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('cols', 'org.esco.grouperui.group.members.person.col', '#{attr[''objectClass'']}', '#{attr[''objectClass'']}', 'No description');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('cols', 'org.esco.grouperui.group.members.person.col', '#{attr[''ESCOUAIRattachement'']} - #{attr[''mail'']}', '#{attr[''ESCOUAIRattachement'']} - #{attr[''mail'']}', 'No description');

INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('', 'org.esco.grouperui.group.right', '', '.label', 'No description');

INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('cols', 'org.esco.grouperui.search.person.col', '#{attr[''attribute.displayName'']}', '#{attr[''attribute.displayName'']}', 'No description');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('cols', 'org.esco.grouperui.search.person.col', '#{attr[''attribute.objectClass'']}', '#{attr[''attribute.objectClass'']}', 'No description');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('cols', 'org.esco.grouperui.search.person.col', '#{attr[''attribute.ESCOUAIRattachement'']} - #{attr[''attribute.mail'']}', '#{attr[''attribute.ESCOUAIRattachement'']} - #{attr[''attribute.mail'']}', 'No description');

INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('sn', 'org.esco.grouperui.person.property.attribut', 'sn', 'sn.label', 'Propriétés de personne - attribut nom');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('givenName', 'org.esco.grouperui.person.property.attribut', 'givenName', 'givenName.label', 'Propriétés de personne - attribut prénom');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('displayName', 'org.esco.grouperui.person.property.attribut', 'displayName', 'displayName.label', 'Propriétés de personne - attribut nom affiché');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTPersonLogin', 'org.esco.grouperui.person.property.attribut', 'ENTPersonLogin', 'ENTPersonLogin.label', 'Propriétés de personne - attribut login');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('uid', 'org.esco.grouperui.person.property.attribut', 'uid', 'uid.label', 'Propriétés de personne - attribut uuid');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTPersonFonctions', 'org.esco.grouperui.person.property.attribut', 'ENTPersonFonctions', 'ENTPersonFonctions.label', 'Propriétés de personne - attribut type');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('sort', 'org.esco.grouperui.person.property.attribut.sort', 'sort', 'sn|givenName|displayName|ENTPersonLogin|uid|ENTPersonFonctions', 'Sorting Attributes');

INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('default', 'org.esco.grouperui.group.attribut.regexp', '/^.+$/', 'GROUP_EDITION_REGEXP_ATTRIBUTE_DEFAULT_ERROR_LABEL', 'Edition de groupe - Attributs - regle de validation par defaut');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('extension', 'org.esco.grouperui.group.attribut.regexp', '/^([^:=\xc0\xc1\xc2\xc3\xc4\xc5\xc7\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\xd1\xd2\xd3\xd4\xd5\xd6\xd9\xda\xdb\xdc\xdd\xe0\xe1\xe2\xe3\xe4\xe5\xe7\xe8\xe9\xea\xeb\xec\xed\xee\xef\xf1\xf2\xf3\xf4\xf5\xf6\xf9\xfa\xfb\xfc\xfd ]+)$/', 'GROUP_EDITION_REGEXP_ATTRIBUTE_EXTENSION_ERROR_LABEL', 'Edition de groupe - Attributs - attribut extension - regle de validation (n''autorise pas les :, accents et espace.)');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('displayExtension', 'org.esco.grouperui.group.attribut.regexp', '/^([^:]+)$/', 'GROUP_EDITION_REGEXP_ATTRIBUTE_DISPLAYEXTENSION_ERROR_LABEL', 'Edition de groupe - Attributs - attribut extension usuelle - regle de validation (n''autorise pas les :)');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('description', 'org.esco.grouperui.group.attribut.regexp', '/^.*$/', 'GROUP_EDITION_REGEXP_ATTRIBUTE_DESCRIPTION_ERROR_LABEL', 'Edition de groupe - Attributs - attribut description - regle de validation');

INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('default', 'org.esco.grouperui.default.rule.regexp', '/^.+$/', 'DEFAULT_RULE_REGEXP_DEFAULT_ERROR_LABEL', 'Regle de validation par defaut - Obligatoire');


INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('cols', 'org.esco.grouperui.search.group.col', '#{attr[''displayExtension'']}', '#{attr[''displayExtension'']}', 'No description');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('cols', 'org.esco.grouperui.search.group.col', '#{attr[''objectClass'']}', '#{attr[''objectClass'']}', 'No description');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('cols', 'org.esco.grouperui.search.group.col', '#{attr[''displayName'']}', '#{attr[''displayName'']}', 'No description');

INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('cols', 'org.esco.grouperui.group.members.group.col', '#{attr[''displayExtension'']}', '#{attr[''displayExtension'']}', 'No description');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('cols', 'org.esco.grouperui.group.members.group.col', '#{attr[''typeSubject'']}', '#{attr[''typeSubject'']}', 'No description');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('cols', 'org.esco.grouperui.group.members.group.col', '#{attr[''displayName'']}', '#{attr[''displayName'']}', 'No description');

INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('extension', 'org.esco.grouperui.group.property.attribut', 'extension', 'extension.label', 'Propriétés de groupe - Attributs - attribut extension');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('displayExtension', 'org.esco.grouperui.group.property.attribut', 'displayExtension', 'displayExtension.label', 'Propriétés de groupe - Attributs - extension usuelle');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('description', 'org.esco.grouperui.group.property.attribut', 'description', 'description.label', 'Propriétés de groupe - Attributs - attribut description');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('uuid', 'org.esco.grouperui.group.property.attribut', 'uuid', 'uuid.label', 'Propriétés de groupe - Attributs - attribut uuid');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('sort', 'org.esco.grouperui.group.property.attribut.sort', 'sort', 'extension|displayExtension|description|uuid', 'Sorting Attributes');

INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ldap', 'org.esco.grouperui.group.dynamic.ldap.search', 'ENTPerson', 'ENTPerson', 'Groupes dynamiques - Base de la recherche');


INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('cols', 'org.esco.grouperui.all.privilege.group.col', '#{attr[''displayExtension'']}', '#{attr[''displayExtension'']}', 'No description');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('cols', 'org.esco.grouperui.all.privilege.group.col', '#{attr[''displayName'']}', '#{attr[''displayName'']}', 'No description');

INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('extension', 'org.esco.grouperui.stem.attribut.creation', 'extension', 'extension.label', 'Creation de dossier - Attributs - attribut extension - attribut obligatoire');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('displayExtension', 'org.esco.grouperui.stem.attribut.creation', 'displayExtension', 'displayExtension.label', 'Creation de dossier - Attributs - attribut extension usuelle - attribut obligatoire');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('description', 'org.esco.grouperui.stem.attribut.creation', 'description', 'description.label', 'Creation de dossier - Attributs - attribut description');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('sort', 'org.esco.grouperui.stem.attribut.creation.sort', 'sort', 'extension|displayExtension|description', 'Sorting Attributes');

INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('displayName', 'org.esco.grouperui.group.members.attribut', 'displayName', 'displayName.label', 'No description');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('org.esco.grouperui.group.members.attribut', 'org.esco.grouperui.group.members.attribut', 'objectClass', 'objectClass', 'No description');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ESCOUAIRattachement', 'org.esco.grouperui.group.members.attribut', 'ESCOUAIRattachement', 'ESCOUAIRattachement.label', 'No description');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('mail', 'org.esco.grouperui.group.members.attribut', 'mail', 'mail.label', 'No description');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('displayExtension', 'org.esco.grouperui.group.members.attribut', 'displayExtension', 'displayExtension.label', 'No description');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('name', 'org.esco.grouperui.group.members.attribut', 'name', 'name.label', 'No description');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('typeSubject', 'org.esco.grouperui.group.members.attribut', 'typeSubject', 'typeSubject.label', 'No description');

INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('cols', 'org.esco.grouperui.stem.privileges.person.col', '#{attr[''displayName'']}', '#{attr[''displayName'']}', 'No description');

INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('base', 'org.esco.grouperui.group.custom.type', 'base', 'base.label', 'Edition de groupe - Attributs - Types personnalisés - base');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('sort', 'org.esco.grouperui.group.custom.type.sort', 'sort', 'base', 'Sorting Attributes');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('default', 'org.esco.grouperui.group.custom.default', 'default', 'base', 'Edition de groupe - Attributs - Types personnalises - defaut type');

INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('searchTerm', 'org.esco.grouperui.search.regexp', '/^.+$/', 'SEARCH_REGEXP_SEARCHTERM_ERROR_LABEL', 'Recherche - Champs de recherche');


INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('cols', 'org.esco.grouperui.ldap.person.col', 'displayName', 'displayName', 'No description');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('cols', 'org.esco.grouperui.ldap.person.col', 'objectClass', 'objectClass', 'No description');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('cols', 'org.esco.grouperui.ldap.person.col', 'ESCOUAIRattachement', 'ESCOUAIRattachement', 'No description');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('cols', 'org.esco.grouperui.ldap.person.col', 'mail', 'mail', 'No description');


INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('extension', 'org.esco.grouperui.group.attribut.modification', 'extension', 'extension.label', 'Modification de groupe - Attributs - attribut extension - attribut obligatoire');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('displayExtension', 'org.esco.grouperui.group.attribut.modification', 'displayExtension', 'displayExtension.label', 'Modification de groupe - Attributs - attribut extension usuelle - attribut obligatoire');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('description', 'org.esco.grouperui.group.attribut.modification', 'description', 'description.label', 'Modification de groupe - Attributs - attribut description');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('sort', 'org.esco.grouperui.group.attribut.modification.sort', 'sort', 'extension|displayExtension|description', 'Sorting Attributes');

INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('default', 'org.esco.grouperui.stem.attribut.regexp', '/^.+$/', 'STEM_EDITION_REGEXP_ATTRIBUTE_DEFAULT_ERROR_LABEL', 'Edition de dossier - Attributs - regle de validation par defaut');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('extension', 'org.esco.grouperui.stem.attribut.regexp', '/^([^:=\xc0\xc1\xc2\xc3\xc4\xc5\xc7\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\xd1\xd2\xd3\xd4\xd5\xd6\xd9\xda\xdb\xdc\xdd\xe0\xe1\xe2\xe3\xe4\xe5\xe7\xe8\xe9\xea\xeb\xec\xed\xee\xef\xf1\xf2\xf3\xf4\xf5\xf6\xf9\xfa\xfb\xfc\xfd ]+)$/', 'STEM_EDITION_REGEXP_ATTRIBUTE_EXTENSION_ERROR_LABEL', 'Edition de dossier - Attributs - attribut extension - regle de validation (n''autorise pas les :, accents et espace.)');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('displayExtension', 'org.esco.grouperui.stem.attribut.regexp', '/^([^:]+)$/', 'STEM_EDITION_REGEXP_ATTRIBUTE_DISPLAYEXTENSION_ERROR_LABEL', 'Edition de dossier - Attributs - attribut extension usuelle - regle de validation (n''autorise pas les :)');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('description', 'org.esco.grouperui.stem.attribut.regexp', '/^.*$/', 'STEM_EDITION_REGEXP_ATTRIBUTE_DESCRIPTION_ERROR_LABEL', 'Edition de dossier - Attributs - attribut description - regle de validation');

INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('cols', 'org.esco.grouperui.search.stem.col', '#{attr[''displayExtension'']}', '#{attr[''displayExtension'']}', 'No description');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('cols', 'org.esco.grouperui.search.stem.col', '#{attr[''displayName'']}', '#{attr[''displayName'']}', 'No description');

INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('extension', 'org.esco.grouperui.stem.attribut.modification', 'extension', 'extension.label', 'Modification de dossier - Attributs - attribut extension - attribut obligatoire');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('displayExtension', 'org.esco.grouperui.stem.attribut.modification', 'displayExtension', 'displayExtension.label', 'Modification de dossier - Attributs - attribut extension usuelle - attribut obligatoire');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('description', 'org.esco.grouperui.stem.attribut.modification', 'description', 'description.label', 'Modification de dossier - Attributs - attribut description');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('sort', 'org.esco.grouperui.stem.attribut.modification.sort', 'sort', 'extension|displayExtension|description', 'Sorting Attributes');

INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('parent', 'org.esco.grouperui.stem.parent.name.regexp', 'parent', '.+', 'Edition de dossier - Attributs - droit pour edition de l attribut extension');


INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('cols', 'org.esco.grouperui.group.privileges.group.col', '#{attr[''displayExtension'']}', '#{attr[''displayExtension'']}', 'No description');

INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('extension', 'org.esco.grouperui.group.attribut.creation', 'extension', 'extension.label', 'Creation de groupe - Attributs - attribut extension - attribut obligatoire');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('displayExtension', 'org.esco.grouperui.group.attribut.creation', 'displayExtension', 'displayExtension.label', 'Creation de groupe - Attributs - attribut extension usuelle - attribut obligatoire');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('description', 'org.esco.grouperui.group.attribut.creation', 'description', 'description.label', 'Creation de groupe - Attributs - attribut description');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('sort', 'org.esco.grouperui.group.attribut.creation.sort', 'sort', 'extension|displayExtension|description', 'Sorting Attributes');

INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('cols', 'org.esco.grouperui.group.privileges.person.col', '#{attr[''displayName'']}', '#{attr[''displayName'']}', 'No description');

INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('cols', 'org.esco.grouperui.all.privilege.stem.col', '#{attr[''displayExtension'']}', '#{attr[''displayExtension'']}', 'No description');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('cols', 'org.esco.grouperui.all.privilege.stem.col', '#{attr[''displayName'']}', '#{attr[''displayName'']}', 'No description');

INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('cols', 'org.esco.grouperui.stem.privileges.group.col', '#{attr[''displayExtension'']}', '#{attr[''displayExtension'']}', 'No description');

INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('cols', 'org.esco.grouperui.person.subscriptions.cols', '#{attr[''displayExtension'']}', '#{attr[''displayExtension'']}', 'No description');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('cols', 'org.esco.grouperui.person.subscriptions.cols', '#{attr[''displayName'']}', '#{attr[''displayName'']}', 'No description');

INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('person', 'org.esco.grouperui.group.privileges.map', 'person', 'esco:ldap', 'Edition de groupe - Privileges - détermination type personne');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('group', 'org.esco.grouperui.group.privileges.map', 'group', 'g:gsa', 'Edition de groupe - Privileges - détermination type groupe');

INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('search_person_in_group_max_result', 'org.esco.grouperui.search.max', 'search_person_in_group_max_result', '200', 'Recherche - Maximum de résultats pour une recherche de personne dans un groupe');


INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('displayName', 'org.esco.grouperui.group.privileges.attribut', 'displayName', 'displayName.label', 'No description');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('displayExtension', 'org.esco.grouperui.group.privileges.attribut', 'displayExtension', 'displayExtension.label', 'No description');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('name', 'org.esco.grouperui.group.privileges.attribut', 'name', 'name.label', 'No description');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('org.esco.grouperui.group.privileges.attribut', 'org.esco.grouperui.group.privileges.attribut', 'objectClass', 'objectClass', 'No description');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('typeSubject', 'org.esco.grouperui.group.privileges.attribut', 'typeSubject', 'typeSubject.label', 'No description');

INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ldap', 'org.esco.grouperui.group.dynamic.ldap.operator', '=', '=', 'Groupes dynamiques - Opérateur égalité');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ldap', 'org.esco.grouperui.group.dynamic.ldap.operator', '!=', '<>', 'Groupes dynamiques - Opérateur différent');


INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('cols', 'org.esco.grouperui.all.memberships.col', '#{attr[''displayExtension'']}', '#{attr[''displayExtension'']}', 'No description');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('cols', 'org.esco.grouperui.all.memberships.col', '#{attr[''displayName'']}', '#{attr[''displayName'']}', 'No description');

INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('person', 'org.esco.grouperui.stem.privileges.map', 'person', 'esco:ldap', 'Edition de dossier - Privileges - détermination type personne');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('group', 'org.esco.grouperui.stem.privileges.map', 'group', 'g:gsa', 'Edition de dossier - Privileges - détermination type groupe');

INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('displayName', 'org.esco.grouperui.stem.privileges.attribut', 'displayName', 'displayName.label', 'No description');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('displayExtension', 'org.esco.grouperui.stem.privileges.attribut', 'displayExtension', 'displayExtension.label', 'No description');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('name', 'org.esco.grouperui.stem.privileges.attribut', 'name', 'name.label', 'No description');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('org.esco.grouperui.stem.privileges.attribut', 'org.esco.grouperui.stem.privileges.attribut', 'objectClass', 'objectClass', 'No description');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('typeSubject', 'org.esco.grouperui.stem.privileges.attribut', 'typeSubject', 'typeSubject.label', 'No description');

INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('extension', 'org.esco.grouperui.stem.property.attribut', 'extension', 'extension.label', 'Propriétés de dossier - attribut extension');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('displayExtension', 'org.esco.grouperui.stem.property.attribut', 'displayExtension', 'displayExtension.label', 'Propriétés de dossier - attribut description');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('description', 'org.esco.grouperui.stem.property.attribut', 'description', 'description.label', 'Propriétés de dossier - tri des attributs');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('uuid', 'org.esco.grouperui.stem.property.attribut', 'uuid', 'uuid.label', 'Propriétés de dossier - attribut uuid');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('sort', 'org.esco.grouperui.stem.property.attribut.sort', 'sort', 'extension|displayExtension|description|uuid', 'Sorting Attributes');


INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ldap', 'org.esco.grouperui.group.dynamic.leftdrop.name', 'objectClass', 'objectClass.label', 'Groupes dynamiques - Types de personnes');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('objectClass', 'org.esco.grouperui.group.dynamic.rightdrop.type', 'wildcard', 'false', 'Groupes dynamiques - Types de personnes - Management wildcard');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('objectClass', 'org.esco.grouperui.group.dynamic.rightdrop.type', 'list', 'true', 'Groupes dynamiques - Types de personnes - Management type');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('objectClass', 'org.esco.grouperui.group.dynamic.rightdrop.list', 'ENTPerson', 'ENTPerson.label', 'Groupes dynamiques - Types de personnes - Management of lists of values');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('objectClass', 'org.esco.grouperui.group.dynamic.rightdrop.list', 'ENTEleve', 'ENTEleve.label', 'Groupes dynamiques - Types de personnes - Management of lists of values');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('objectClass', 'org.esco.grouperui.group.dynamic.rightdrop.list', 'ENTAuxEnseignant', 'ENTAuxEnseignant.label', 'Groupes dynamiques - Types de personnes - Management of lists of values');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('objectClass', 'org.esco.grouperui.group.dynamic.rightdrop.list', 'ENTAuxPersRelEleve', 'ENTAuxPersRelEleve.label', 'Groupes dynamiques - Types de personnes - Management of lists of values');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ldap', 'org.esco.grouperui.group.dynamic.leftdrop.name', 'sn', 'sn.label', 'Groupes dynamiques - Nom');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('sn', 'org.esco.grouperui.group.dynamic.rightdrop.type', 'wildcard', 'true', 'Groupes dynamiques - Nom - Management wildcard');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('sn', 'org.esco.grouperui.group.dynamic.rightdrop.type', 'input', 'true', 'Groupes dynamiques - Nom - Management type');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ldap', 'org.esco.grouperui.group.dynamic.leftdrop.name', 'ENTPersonSexe', 'ENTPersonSexe.label', 'Groupes dynamiques - Sexe');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTPersonSexe', 'org.esco.grouperui.group.dynamic.rightdrop.type', 'wildcard', 'false', 'Groupes dynamiques - Sexe - Management wildcard');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTPersonSexe', 'org.esco.grouperui.group.dynamic.rightdrop.type', 'list', 'true', 'Groupes dynamiques - Sexe - Management type');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTPersonSexe', 'org.esco.grouperui.group.dynamic.rightdrop.list', 'M', 'M.label', 'Groupes dynamiques - Sexe - Management of lists of values');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTPersonSexe', 'org.esco.grouperui.group.dynamic.rightdrop.list', 'F', 'F.label', 'Groupes dynamiques - Sexe - Management of lists of values');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ldap', 'org.esco.grouperui.group.dynamic.leftdrop.name', 'ENTPersonVille', 'ENTPersonVille.label', 'Groupes dynamiques - Ville');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTPersonVille', 'org.esco.grouperui.group.dynamic.rightdrop.type', 'wildcard', 'true', 'Groupes dynamiques - Ville - Management wildcard');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTPersonVille', 'org.esco.grouperui.group.dynamic.rightdrop.type', 'input', 'true', 'Groupes dynamiques - Ville - Management type');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ldap', 'org.esco.grouperui.group.dynamic.leftdrop.name', 'ENTPersonProfils', 'ENTPersonProfils.label', 'Groupes dynamiques - Profils national');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTPersonProfils', 'org.esco.grouperui.group.dynamic.rightdrop.type', 'wildcard', 'true', 'Groupes dynamiques - Profils national - Management wildcard');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTPersonProfils', 'org.esco.grouperui.group.dynamic.rightdrop.type', 'list', 'true', 'Groupes dynamiques - Profils national - Management type');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTPersonProfils', 'org.esco.grouperui.group.dynamic.rightdrop.list', 'National_1', 'National_1.label', 'Groupes dynamiques - Profils national - Management of lists of values');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTPersonProfils', 'org.esco.grouperui.group.dynamic.rightdrop.list', 'National_2', 'National_2.label', 'Groupes dynamiques - Profils national - Management of lists of values');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTPersonProfils', 'org.esco.grouperui.group.dynamic.rightdrop.list', 'National_3', 'National_3.label', 'Groupes dynamiques - Profils national - Management of lists of values');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTPersonProfils', 'org.esco.grouperui.group.dynamic.rightdrop.list', 'National_4', 'National_4.label', 'Groupes dynamiques - Profils national - Management of lists of values');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTPersonProfils', 'org.esco.grouperui.group.dynamic.rightdrop.list', 'National_5', 'National_5.label', 'Groupes dynamiques - Profils national - Management of lists of values');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTPersonProfils', 'org.esco.grouperui.group.dynamic.rightdrop.list', 'National_6', 'National_6.label', 'Groupes dynamiques - Profils national - Management of lists of values');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ldap', 'org.esco.grouperui.group.dynamic.leftdrop.name', 'ENTPersonStructRattach', 'ENTPersonStructRattach.label', 'Groupes dynamiques - Structure de rattachement');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTPersonStructRattach', 'org.esco.grouperui.group.dynamic.rightdrop.type', 'wildcard', 'false', 'Groupes dynamiques - Structure de rattachement - Management wildcard');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTPersonStructRattach', 'org.esco.grouperui.group.dynamic.rightdrop.type', 'input', 'true', 'Groupes dynamiques - Structure de rattachement - Management type');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ldap', 'org.esco.grouperui.group.dynamic.leftdrop.name', 'ENTEleveBoursier', 'ENTEleveBoursier.label', 'Groupes dynamiques - Eleve boursier');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTEleveBoursier', 'org.esco.grouperui.group.dynamic.rightdrop.type', 'wildcard', 'false', 'Groupes dynamiques - Eleve boursier - Management wildcard');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTEleveBoursier', 'org.esco.grouperui.group.dynamic.rightdrop.type', 'list', 'true', 'Groupes dynamiques - Eleve boursier - Management type');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTEleveBoursier', 'org.esco.grouperui.group.dynamic.rightdrop.list', 'O', 'O.label', 'Groupes dynamiques - Eleve boursier - Management of lists of values');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTEleveBoursier', 'org.esco.grouperui.group.dynamic.rightdrop.list', 'N', 'N.label', 'Groupes dynamiques - Eleve boursier - Management of lists of values');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ldap', 'org.esco.grouperui.group.dynamic.leftdrop.name', 'ENTEleveMajeur', 'ENTEleveMajeur.label', 'Groupes dynamiques - Majeur');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTEleveMajeur', 'org.esco.grouperui.group.dynamic.rightdrop.type', 'wildcard', 'false', 'Groupes dynamiques - Majeur - Management wildcard');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTEleveMajeur', 'org.esco.grouperui.group.dynamic.rightdrop.type', 'list', 'true', 'Groupes dynamiques - Majeur - Management type');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTEleveMajeur', 'org.esco.grouperui.group.dynamic.rightdrop.list', 'O', 'O.label', 'Groupes dynamiques - Majeur - Management of lists of values');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTEleveMajeur', 'org.esco.grouperui.group.dynamic.rightdrop.list', 'N', 'N.label', 'Groupes dynamiques - Majeur - Management of lists of values');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ldap', 'org.esco.grouperui.group.dynamic.leftdrop.name', 'ENTEleveTransport', 'ENTEleveTransport.label', 'Groupes dynamiques - Utilise transports en commun');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTEleveTransport', 'org.esco.grouperui.group.dynamic.rightdrop.type', 'wildcard', 'false', 'Groupes dynamiques - Utilise transports en commun - Management wildcard');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTEleveTransport', 'org.esco.grouperui.group.dynamic.rightdrop.type', 'list', 'true', 'Groupes dynamiques - Utilise transports en commun - Management type');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTEleveTransport', 'org.esco.grouperui.group.dynamic.rightdrop.list', 'O', 'O.label', 'Groupes dynamiques - Utilise transports en commun - Management of lists of values');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTEleveTransport', 'org.esco.grouperui.group.dynamic.rightdrop.list', 'N', 'N.label', 'Groupes dynamiques - Utilise transports en commun - Management of lists of values');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ldap', 'org.esco.grouperui.group.dynamic.leftdrop.name', 'ENTEleveClasses', 'ENTEleveClasses.label', 'Groupes dynamiques - Classe de l eleve');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTEleveClasses', 'org.esco.grouperui.group.dynamic.rightdrop.type', 'wildcard', 'true', 'Groupes dynamiques - Classe de l eleve - Management wildcard');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTEleveClasses', 'org.esco.grouperui.group.dynamic.rightdrop.type', 'input', 'true', 'Groupes dynamiques - Classe de l eleve - Management type');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ldap', 'org.esco.grouperui.group.dynamic.leftdrop.name', 'ENTEleveEnseignements', 'ENTEleveEnseignements.label', 'Groupes dynamiques - Enseignements suivis');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTEleveEnseignements', 'org.esco.grouperui.group.dynamic.rightdrop.type', 'wildcard', 'true', 'Groupes dynamiques - Enseignements suivis - Management wildcard');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTEleveEnseignements', 'org.esco.grouperui.group.dynamic.rightdrop.type', 'input', 'true', 'Groupes dynamiques - Enseignements suivis - Management type');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ldap', 'org.esco.grouperui.group.dynamic.leftdrop.name', 'ENTEleveFiliere', 'ENTEleveFiliere.label', 'Groupes dynamiques - Filiere suivie');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTEleveFiliere', 'org.esco.grouperui.group.dynamic.rightdrop.type', 'wildcard', 'true', 'Groupes dynamiques - Filiere suivie - Management wildcard');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTEleveFiliere', 'org.esco.grouperui.group.dynamic.rightdrop.type', 'input', 'true', 'Groupes dynamiques - Filiere suivie - Management type');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ldap', 'org.esco.grouperui.group.dynamic.leftdrop.name', 'ENTEleveRegime', 'ENTEleveRegime.label', 'Groupes dynamiques - Regime de l eleve');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTEleveRegime', 'org.esco.grouperui.group.dynamic.rightdrop.type', 'wildcard', 'true', 'Groupes dynamiques - Regime de l eleve - Management wildcard');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTEleveRegime', 'org.esco.grouperui.group.dynamic.rightdrop.type', 'input', 'true', 'Groupes dynamiques - Regime de l eleve - Management type');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ldap', 'org.esco.grouperui.group.dynamic.leftdrop.name', 'ENTEleveStatutEleve', 'ENTEleveStatutEleve.label', 'Groupes dynamiques - Statut de l eleve');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTEleveStatutEleve', 'org.esco.grouperui.group.dynamic.rightdrop.type', 'wildcard', 'true', 'Groupes dynamiques - Statut de l eleve - Management wildcard');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTEleveStatutEleve', 'org.esco.grouperui.group.dynamic.rightdrop.type', 'input', 'true', 'Groupes dynamiques - Statut de l eleve - Management type');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ldap', 'org.esco.grouperui.group.dynamic.leftdrop.name', 'ENTAuxEnsClasses', 'ENTAuxEnsClasses.label', 'Groupes dynamiques - Classes de l enseignant');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTAuxEnsClasses', 'org.esco.grouperui.group.dynamic.rightdrop.type', 'wildcard', 'true', 'Groupes dynamiques - Classes de l enseignant - Management wildcard');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTAuxEnsClasses', 'org.esco.grouperui.group.dynamic.rightdrop.type', 'input', 'true', 'Groupes dynamiques - Classes de l enseignant - Management type');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ldap', 'org.esco.grouperui.group.dynamic.leftdrop.name', 'ENTAuxEnsMEF', 'ENTAuxEnsMEF.label', 'Groupes dynamiques - MEF de l enseignant');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTAuxEnsMEF', 'org.esco.grouperui.group.dynamic.rightdrop.type', 'wildcard', 'true', 'Groupes dynamiques - MEF de l enseignant - Management wildcard');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTAuxEnsMEF', 'org.esco.grouperui.group.dynamic.rightdrop.type', 'input', 'true', 'Groupes dynamiques - MEF de l enseignant - Management type');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ldap', 'org.esco.grouperui.group.dynamic.leftdrop.name', 'ENTAuxEnsCategoDiscipline', 'ENTAuxEnsCategoDiscipline.label', 'Groupes dynamiques - Categories de disciplines enseignees');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTAuxEnsCategoDiscipline', 'org.esco.grouperui.group.dynamic.rightdrop.type', 'wildcard', 'true', 'Groupes dynamiques - Categories de disciplines enseignees - Management wildcard');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTAuxEnsCategoDiscipline', 'org.esco.grouperui.group.dynamic.rightdrop.type', 'input', 'true', 'Groupes dynamiques - Categories de disciplines enseignees - Management type');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ldap', 'org.esco.grouperui.group.dynamic.leftdrop.name', 'ENTAuxEnsClassesPrincipal', 'ENTAuxEnsClassesPrincipal.label', 'Groupes dynamiques - Principal des classes');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTAuxEnsClassesPrincipal', 'org.esco.grouperui.group.dynamic.rightdrop.type', 'wildcard', 'true', 'Groupes dynamiques - Principal des classes - Management wildcard');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ENTAuxEnsClassesPrincipal', 'org.esco.grouperui.group.dynamic.rightdrop.type', 'input', 'true', 'Groupes dynamiques - Principal des classes - Management type');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ldap', 'org.esco.grouperui.group.dynamic.leftdrop.name', 'ESCOUAI', 'ESCOUAI.label', 'Groupes dynamiques - N UAI des etablissements associes');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ESCOUAI', 'org.esco.grouperui.group.dynamic.rightdrop.type', 'wildcard', 'false', 'Groupes dynamiques - N UAI des etablissements associes - Management wildcard');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ESCOUAI', 'org.esco.grouperui.group.dynamic.rightdrop.type', 'list', 'true', 'Groupes dynamiques - N UAI des etablissements associes - Management type');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ESCOUAI', 'org.esco.grouperui.group.dynamic.rightdrop.list', '0189999W', '0189999W.label', 'Groupes dynamiques - N UAI des etablissements associes - Management of lists of values');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ESCOUAI', 'org.esco.grouperui.group.dynamic.rightdrop.list', '0289999S', '0289999S.label', 'Groupes dynamiques - N UAI des etablissements associes - Management of lists of values');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ESCOUAI', 'org.esco.grouperui.group.dynamic.rightdrop.list', '0370001A', '0370001A.label', 'Groupes dynamiques - N UAI des etablissements associes - Management of lists of values');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ESCOUAI', 'org.esco.grouperui.group.dynamic.rightdrop.list', '0379999T', '0379999T.label', 'Groupes dynamiques - N UAI des etablissements associes - Management of lists of values');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ESCOUAI', 'org.esco.grouperui.group.dynamic.rightdrop.list', '0410017W', '0410017W.label', 'Groupes dynamiques - N UAI des etablissements associes - Management of lists of values');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ESCOUAI', 'org.esco.grouperui.group.dynamic.rightdrop.list', '0419999W', '0419999W.label', 'Groupes dynamiques - N UAI des etablissements associes - Management of lists of values');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ESCOUAI', 'org.esco.grouperui.group.dynamic.rightdrop.list', '0450080T', '0450080T.label', 'Groupes dynamiques - N UAI des etablissements associes - Management of lists of values');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ESCOUAI', 'org.esco.grouperui.group.dynamic.rightdrop.list', '0459999Z', '0459999Z.label', 'Groupes dynamiques - N UAI des etablissements associes - Management of lists of values');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ldap', 'org.esco.grouperui.group.dynamic.leftdrop.name', 'ESCOUAIRattachement', 'ESCOUAIRattachement.label', 'Groupes dynamiques - N UAI de l etablissement de rattachement');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ESCOUAIRattachement', 'org.esco.grouperui.group.dynamic.rightdrop.type', 'wildcard', 'false', 'Groupes dynamiques - N UAI de l etablissement de rattachement - Management wildcard');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ESCOUAIRattachement', 'org.esco.grouperui.group.dynamic.rightdrop.type', 'list', 'true', 'Groupes dynamiques - N UAI de l etablissement de rattachement - Management type');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ESCOUAIRattachement', 'org.esco.grouperui.group.dynamic.rightdrop.list', '0189999W', '0189999W.label', 'Groupes dynamiques - N UAI de l etablissement de rattachement - Management of lists of values');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ESCOUAIRattachement', 'org.esco.grouperui.group.dynamic.rightdrop.list', '0289999S', '0289999S.label', 'Groupes dynamiques - N UAI de l etablissement de rattachement - Management of lists of values');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ESCOUAIRattachement', 'org.esco.grouperui.group.dynamic.rightdrop.list', '0370001A', '0370001A.label', 'Groupes dynamiques - N UAI de l etablissement de rattachement - Management of lists of values');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ESCOUAIRattachement', 'org.esco.grouperui.group.dynamic.rightdrop.list', '0379999T', '0379999T.label', 'Groupes dynamiques - N UAI de l etablissement de rattachement - Management of lists of values');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ESCOUAIRattachement', 'org.esco.grouperui.group.dynamic.rightdrop.list', '0410017W', '0410017W.label', 'Groupes dynamiques - N UAI de l etablissement de rattachement - Management of lists of values');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ESCOUAIRattachement', 'org.esco.grouperui.group.dynamic.rightdrop.list', '0419999W', '0419999W.label', 'Groupes dynamiques - N UAI de l etablissement de rattachement - Management of lists of values');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ESCOUAIRattachement', 'org.esco.grouperui.group.dynamic.rightdrop.list', '0450080T', '0450080T.label', 'Groupes dynamiques - N UAI de l etablissement de rattachement - Management of lists of values');
INSERT INTO "DBPARAMETER"."PARAM" ("PKEY", "PGROUP", "PARAM_KEY", "PARAM_VALUE", "PARAM_COMMENT") VALUES ('ESCOUAIRattachement', 'org.esco.grouperui.group.dynamic.rightdrop.list', '0459999Z', '0459999Z.label', 'Groupes dynamiques - N UAI de l etablissement de rattachement - Management of lists of values');

